export default {
  ACCESS_INDEX_API: 'ACCESS_INDEX_API',
  RETRIEVE: 'RETRIEVE',
  SCHEDULER_UPDATE_START: 'SCHEDULER_UPDATE_START',
  SCHEDULER_UPDATE_END: 'SCHEDULER_UPDATE_END',
  ON_DEMAND_UPDATE_START: 'ON_DEMAND_UPDATE_START',
  ON_DEMAND_UPDATE_END: 'ON_DEMAND_UPDATE_END',
  ERROR_SCHEDULER_UPDATE: 'ERROR_SCHEDULER_UPDATE',
  DB_CLEAR: 'DB_CLEAR',

  // Error Events
  ERROR_ON_DEMAND_UPDATE: 'ERROR_ON_DEMAND_UPDATE',
  ERROR_API: 'ERROR_API',
}
